name = "mcp-registry-office"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "REGISTRY_KV"
id = "7bb3837b12b747fd88c314acb59a8365"

[vars]
UPSTREAM_REGISTRY = "https://registry.modelcontextprotocol.io"
ALLOW_ORIGIN = "*"

[observability]
enabled = true
